name: Deploy to EC2
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: ./gradlew clean bootJar -x test
      
      - run: |
          IMAGE=chat27/my-app:${{ github.sha }}
          docker build -t $IMAGE .
          docker push $IMAGE

      - uses: appleboy/ssh-action@master
        env:
          IMAGE: chat27/my-app:${{ github.sha }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull $IMAGE
            sudo docker stop my-app || true
            sudo docker rm   my-app || true
            sudo docker run -d --name my-app -p 8080:8080 $IMAGE
