name: Run Test
on:
  push:
    branches:
      - '*/*'
      - main  
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: gradle

      - run: ./gradlew clean test --info

      - name: Publish test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/test-results/test
      

  
